name: Run Tests

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: Run SuperTest API tests
        working-directory: automation-frameworks/api-automation/supertest
        run: |
          npm ci || true
          npm test || true
      - name: Run Playwright UI tests
        working-directory: automation-frameworks/ui-automation/playwright
        run: |
          npm ci || true
          npx playwright install --with-deps
          npx playwright test || true
